packages:
  - playground
  - test/fixtures/layers
  - test/fixtures/layers/packages/*

shamefullyHoist: true
strictPeerDependencies: false

allowBuilds:
  esbuild: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - nuxt-state@0.0.1
